networks:
  db:
    name: b2b-db-network

services:
  app:
    container_name: b2b-app
    image: b2b-app-image
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.4'
          memory: 100M
    entrypoint:
      - /app/manage.py
    command:
      - runserver
      - 0.0.0.0:8000
    networks:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./b2btest:/app
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: b2b-db
    image: mysql:9.0.1
    env_file:
      - ./.env
    networks:
      - db
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 5s
      retries: 5
      timeout: 10s
